import type { IconType } from 'react-icons';
import {
  FaGithub,
  FaLinkedin,
  FaWhatsapp,
  FaEnvelope,
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaNodeJs,
  FaPhp,
  FaPython,
  FaGitAlt,
  FaFigma,
  FaTools,
  FaServer,
  FaDatabase,
  FaCode,
  FaPenNib,
  FaImage,
  FaPalette,
  FaShapes,
  FaGraduationCap,
  FaBriefcase,
  FaLaptopCode,
  FaUserTie,
  FaStar,
  FaExternalLinkAlt,
  FaDownload,
  FaSun,
  FaMoon,
  FaBars,
  FaTimes,
  FaGlobe,
  FaLayerGroup,
  FaCheckCircle,
  FaExclamationCircle,
} from 'react-icons/fa';
import {
  SiTypescript,
  SiTailwindcss,
  SiBootstrap,
  SiNestjs,
  SiDjango,
  SiMysql,
  SiPostgresql,
  SiSqlite,
  SiPrisma,
  
  SiPostman,
} from 'react-icons/si';
export const iconMap: Record<string, IconType> = {
  github: FaGithub,
  linkedin: FaLinkedin,
  whatsapp: FaWhatsapp,
  email: FaEnvelope,
  html5: FaHtml5,
  css3: FaCss3Alt,
  javascript: FaJs,
  typescript: SiTypescript,
  react: FaReact,
  tailwind: SiTailwindcss,
  bootstrap: SiBootstrap,
  nodejs: FaNodeJs,
  nestjs: SiNestjs,
  php: FaPhp,
  python: FaPython,
  django: SiDjango,
  api: FaServer,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  sqlite: SiSqlite,
  prisma: SiPrisma,
  git: FaGitAlt,
  vscode: FaLaptopCode,
  figma: FaFigma,
  photoshop: FaImage,
  illustrator: FaPalette,
    canva: FaPalette,
  postman: SiPostman,
  tools: FaTools,
  server: FaServer,
  database: FaDatabase,
  code: FaCode,
  penTool: FaPenNib,
  image: FaImage,
  palette: FaPalette,
  shape: FaShapes,
  education: FaGraduationCap,
  freelance: FaBriefcase,
  project: FaLaptopCode,
  internship: FaUserTie,
  star: FaStar,
  externalLink: FaExternalLinkAlt,
  download: FaDownload,
  sun: FaSun,
  moon: FaMoon,
  menu: FaBars,
  close: FaTimes,
  globe: FaGlobe,
  layers: FaLayerGroup,
  success: FaCheckCircle,
  error: FaExclamationCircle,
};

export function getIcon(key: string): IconType {
  return iconMap[key] ?? FaCode;
}
